### ISSUE TITLE
Propagace partnerů a Helceletky

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/robotickytabor.cz#2]
Navrhuji na web ještě přidat část pro partnery a prakticky převzít to, co máme na [mickoflus.cz](www.mickoflus.cz/#team) + přidal bych tam někam loga Robotárny a Helceletky.

**Comment by yaqwsx** [comment]
Za mě Helceletka ano, ostatní partnery bych zvážil. Přemýšlím totiž jestli
tato preventivní propagace působí dobře na účastníky nebo ne.

čt 10. 1. 2019 15:10 odesílatel Jaroslav Páral <notifications@github.com>
napsal:

**Comment by JarekParal** [comment]
Podle mě by to mohlo mít podobný efekt, jako #3?

Vem si, že můžeme napsat, že našimi partnery (podporovateli tábora) jsou Honeywell, Red Hat, SOS, FabLab Brno. To není špatná vizitka ne?

**Comment by mkousal** [comment]
Partneři jsou doplněni, jen nevím kam dát Helceletku a logo Robotárny? 
Jestli logo robotárny (ozubené kolečko) může být vlevo nahoře jako klikatelný odkaz spolu s textem Robotický tábor?

**Comment by JarekParal** [comment]
Loga Robotárny a Helceletky by měli být kompletní - jak obrázek, tak text. Dle součásného grafického manuálu není dovoleno používat samostatně jen obrázek bez textu (výjimku má jen náhledový FB obrázek a pravděpodobně i fav ikonka).

Navrhuji přidat proklikávaci loga Robotárny a Helceletky do této oblasti (pod odstavec s textem "Kdo jsme a co děláme?"):
![image](https://user-images.githubusercontent.com/6726556/51074587-39edf880-1681-11e9-8da7-831445725215.png)
Zároveň bych jako fav ikonku upřednostňoval oficiální logo Robotárný. Lze ho najít na `GDrive\Robotika\Robotárna Helceletova\_Helceletka loga, fonty, hlav. papíry\loga\Robotárna`.

**Comment by JarekParal** [comment]
a6fc98f0299709462ca1e203d92bf8a4c8897dd9
