### ISSUE TITLE
Nastavit .htaccess na HTTPS

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/robotickytabor.cz#5]
Potřebujeme nastavit přesměrování z HTTP na HTTPS v souboru `.htaccess`, tak aby kdokoliv přišel na web šel přes HTTPS. Myslím, že by to mělo pomoct k lepšímu Google Page Ranku, ...

![image](https://user-images.githubusercontent.com/6726556/52050549-2bdd1a80-2551-11e9-836b-692683aa002e.png)

**Comment by yaqwsx** [comment]
Hotovo.
