### ISSUE TITLE
Překlad do angličtiny?

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/robotickytabor.cz#6]
Co si myslíte o překladu webu do angličtiny? Když už je přeložen www.mickoflus.cz

Měl by na to někdo čas? @bsaid ?

**Comment by bsaid** [comment]
Čas si na to najdu. Jak byste v anglické verzi zdůraznili, že tábor reálně běží jen v češtině?

**Comment by JarekParal** [comment]
Dal bych to hned do první věty na webu (viz označená věta v textu):
![image](https://user-images.githubusercontent.com/6726556/56519352-21c02c00-6542-11e9-8202-8a39445de40f.png)

Něco jako: `Czech robotics camp ...`

**Comment by bsaid** [comment]
Fixed as 293d226a41ead5efe523783141bdc74a9628b515.

**Comment by JarekParal** [comment]
Dobrá práce @bsaid.

Nepřidáme tam ještě nějakou poznámku v tomto stylu:
![image](https://user-images.githubusercontent.com/6726556/57144668-d8819f00-6dc1-11e9-8cca-85915231ffc9.png)

**Comment by bsaid** [comment]
Done. de81d57c048ae2f493c9bd1d77e06e3ae73f8ba2
